import React, { useEffect } from 'react';

const PrivacyPolicyPage = () => {
  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);

  return (
    <div style={{ background: '#fff', minHeight: '100vh', paddingTop: 80 }}>
      <style>{`
        .pp-wrap { max-width: 920px; margin: 0 auto; padding: 28px 18px; }
        .pp-header { border-bottom: 1px solid rgba(0,0,0,0.06); }
        .pp-h1 { margin: 0 0 8px; font-size: 28px; font-weight: 800; letter-spacing: -0.02em; color: #7c3aed; }
        .pp-meta { color: #6b7280; font-size: 14px; }
        .pp-muted { color: #6b7280; }
        .pp-card { background: rgba(124,58,237,0.04); border: 1px solid rgba(0,0,0,0.06); border-radius: 12px; padding: 18px; margin: 18px 0; }
        .pp-card h2 { font-size: 18px; font-weight: 700; margin: 0 0 10px; letter-spacing: -0.01em; color: #7c3aed; }
        .pp-card h3 { font-size: 15px; font-weight: 700; margin: 14px 0 8px; }
        .pp-card ul { padding-left: 18px; margin: 8px 0; }
        .pp-card a { color: #7c3aed; text-decoration: none; }
        .pp-card a:hover { text-decoration: underline; }
        .pp-toc a { display: inline-block; margin: 6px 10px 0 0; font-size: 14px; color: #7c3aed; text-decoration: none; }
        .pp-toc a:hover { text-decoration: underline; }
        .pp-pill { display: inline-block; background: rgba(124,58,237,0.08); border: 1px solid rgba(124,58,237,0.18); border-radius: 999px; padding: 6px 12px; margin-right: 8px; margin-top: 8px; font-size: 13px; font-weight: 600; color: #7c3aed; }
        .pp-footer { border-top: 1px solid rgba(0,0,0,0.06); margin-top: 24px; }
      `}</style>

      <div className="pp-header">
        <div className="pp-wrap">
          <h1 className="pp-h1">KoshaX Privacy Policy</h1>
          <div className="pp-meta">
            <span><strong>Last Updated:</strong> <span className="pp-muted">16th March 2026</span></span>
          </div>
          <div className="pp-muted" style={{ marginTop: 10 }}>
            This Privacy Policy describes how KoshaX Technologies Private Limited, a company incorporated under the
            Companies Act, 2013, having its registered office at WeWork Eldeco Centre, Block A, Shivalik Colony, Malviya
            Nagar (South Delhi), New Delhi, South Delhi- 110017, Delhi ("KoshaX", "Company", "we", "our", or "us"),
            collects, uses, stores, processes, and protects personal information when users access or use the KoshaX
            website, applications, software tools, APIs, and related services (collectively referred to as the "Platform").
          </div>
          <div className="pp-muted" style={{ marginTop: 10 }}>
            KoshaX operates as a technology platform designed to assist users in organizing information, managing digital
            knowledge, generating insights, and enabling productivity through intelligent tools and automated systems.
          </div>
          <div className="pp-muted" style={{ marginTop: 10 }}>
            This Privacy Policy applies to all individuals who access or browse the Platform, create an account, use any
            features or services of the Platform, or communicate with KoshaX.
          </div>
          <div className="pp-muted" style={{ marginTop: 10 }}>
            By accessing or using the Platform, you acknowledge that you have read and understood this Privacy Policy and
            consent to the collection and processing of your information in accordance with this Policy and applicable laws.
          </div>

          <div className="pp-toc" style={{ marginTop: 16 }}>
            <a href="#definitions">1. Definitions</a>
            <a href="#collect">2. Information We Collect</a>
            <a href="#use">3. How We Use Information</a>
            <a href="#ai">4. AI-Enabled Features</a>
            <a href="#sharing">5. Sharing &amp; Disclosure</a>
            <a href="#transfers">6. Data Transfers</a>
            <a href="#security">7. Data Security</a>
            <a href="#retention">8. Data Retention</a>
            <a href="#rights">9. User Rights</a>
            <a href="#kids">10. Children's Privacy</a>
            <a href="#thirdparty">11. Third-Party Links</a>
            <a href="#changes">12. Changes</a>
            <a href="#governing">13. Governing Law</a>
            <a href="#contact">14. Contact</a>
          </div>
        </div>
      </div>

      <div className="pp-wrap">

        <div className="pp-card" id="definitions">
          <h2>1. Definitions</h2>
          <ul>
            <li><strong>"Personal Data"</strong> means any information that relates to an identified or identifiable individual.</li>
            <li><strong>"User"</strong> means any individual who accesses or uses the Platform.</li>
            <li><strong>"User Content"</strong> refers to information, files, notes, tasks, prompts, documents, or other data uploaded, submitted, or generated by users on the Platform.</li>
            <li><strong>"Processing"</strong> means any operation performed on personal data including collection, storage, analysis, transmission, or deletion.</li>
          </ul>
        </div>

        <div className="pp-card" id="collect">
          <h2>2. Information We Collect</h2>

          <h3>3.1 Information Provided by Users</h3>
          <p>When you create an account or interact with the Platform, you may provide information including:</p>
          <ul>
            <li>Name</li>
            <li>Email address</li>
            <li>Account credentials</li>
            <li>Profile information</li>
            <li>Communications or support inquiries</li>
            <li>Notes, reminders, tasks, or other information entered into the Platform</li>
            <li>Documents or files uploaded to the Platform</li>
          </ul>
          <p className="pp-muted">Users remain responsible for ensuring that any information uploaded to the Platform complies with applicable laws and does not infringe the rights of third parties.</p>

          <h3>3.2 Usage and Device Information</h3>
          <p>When users access the Platform, certain information may be automatically collected, including:</p>
          <ul>
            <li>IP address</li>
            <li>Browser type and version</li>
            <li>Device type and operating system</li>
            <li>Session timestamps</li>
            <li>System logs and diagnostic data</li>
            <li>Feature usage patterns</li>
          </ul>

          <h3>3.3 Platform Interaction Data</h3>
          <p>We may collect information relating to how users interact with the Platform, such as:</p>
          <ul>
            <li>Navigation behavior</li>
            <li>Interactions with tools or features</li>
            <li>Frequency of usage</li>
            <li>Preferences or configuration settings</li>
          </ul>

          <h3>3.4 Information from Third-Party Integrations</h3>
          <p>If users connect third-party services or applications to the Platform, KoshaX may receive information from those services as permitted by the user and in accordance with the privacy policies of those third parties.</p>
        </div>

        <div className="pp-card" id="use">
          <h2>3. How We Use Information</h2>
          <p>KoshaX may use collected information for the following purposes:</p>
          <ul>
            <li><strong>Platform Operations:</strong> To provide, maintain, and operate the Platform.</li>
            <li><strong>Account Management:</strong> To create and manage user accounts and authentication systems.</li>
            <li><strong>Service Delivery:</strong> To enable users to create, store, organize, and process information using the Platform.</li>
            <li><strong>Product Improvement:</strong> To improve features, usability, performance, and reliability.</li>
            <li><strong>Customer Support:</strong> To respond to inquiries, troubleshoot issues, and provide assistance.</li>
            <li><strong>Security and Fraud Prevention:</strong> To detect and prevent fraud, abuse, unauthorized activity, or security incidents.</li>
            <li><strong>Compliance:</strong> To comply with legal obligations, regulatory requirements, or lawful government requests.</li>
            <li><strong>Research and Development:</strong> To develop new features, services, and technological improvements.</li>
          </ul>
          <p className="pp-muted">We may also use aggregated or anonymized data for analytical and product development purposes.</p>
        </div>

        <div className="pp-card" id="ai">
          <h2>4. Processing of User Content and AI-Enabled Features</h2>
          <p>KoshaX provides tools that may involve automated systems, algorithms, or artificial intelligence technologies designed to assist users in organizing and retrieving information.</p>
          <p>When users upload or input content on the Platform:</p>
          <ul>
            <li>the Platform may analyze such content using automated processing</li>
            <li>the processing may generate insights, suggestions, or structured outputs</li>
          </ul>
          <p>This processing is performed solely for the purpose of providing Platform functionality and improving the user experience.</p>
          <p>KoshaX does not claim ownership of User Content. However, by using the Platform, users grant KoshaX a limited, non-exclusive license to process, store, and analyze User Content solely for the purpose of operating and improving the Platform.</p>
        </div>

        <div className="pp-card" id="sharing">
          <h2>5. Sharing and Disclosure of Information</h2>
          <div className="pp-pill">No sale of personal data</div>
          <p style={{ marginTop: 12 }}>KoshaX does not sell personal data to third parties. However, information may be shared under the following circumstances:</p>

          <h3>Service Providers</h3>
          <p>KoshaX may engage trusted third-party service providers to support the operation, maintenance, and improvement of the Platform. These may include providers of cloud infrastructure, data hosting, analytics, security monitoring, communication services, customer support tools, and artificial intelligence or machine learning services, including large language model (LLM) providers.</p>
          <p>Where Service Providers process personal data or User Content, they do so on behalf of KoshaX and are subject to appropriate contractual obligations, including confidentiality, data protection, and security requirements. KoshaX implements reasonable safeguards to limit data sharing to what is necessary for the provision of services. Where applicable, KoshaX seeks to ensure that such Service Providers do not use personal data for their own independent purposes, except as required for service provision or as permitted under applicable law.</p>

          <h3>Legal and Regulatory Requirements</h3>
          <p>KoshaX may disclose information where required by law, court order, regulatory authorities, or lawful government requests.</p>

          <h3>Protection of Rights</h3>
          <p>Information may be disclosed where necessary to enforce our terms of service, investigate fraud or abuse, protect the safety of users or the public, or protect the rights and property of KoshaX.</p>

          <h3>Business Transfers</h3>
          <p>If KoshaX undergoes a merger, acquisition, restructuring, or sale of assets, user information may be transferred as part of the transaction subject to appropriate confidentiality protections.</p>

          <h3>Third-Party Services</h3>
          <ul>
            <li>OpenAI - AI/LLM processing</li>
            <li>Google Gemini - AI/LLM processing</li>
            <li>Karix - WhatsApp messaging services</li>
            <li>AWS - Cloud Infrastructure</li>
          </ul>
        </div>

        <div className="pp-card" id="transfers">
          <h2>6. Data Storage and International Transfers</h2>
          <p>KoshaX may store and process information using cloud infrastructure and service providers located in various jurisdictions. As a result, information may be transferred and processed outside the user's country of residence.</p>
          <p className="pp-muted">KoshaX ensures that such transfers occur in accordance with applicable legal requirements and that appropriate safeguards are implemented to protect user information.</p>
        </div>

        <div className="pp-card" id="security">
          <h2>7. Data Security</h2>
          <p>KoshaX implements reasonable administrative, technical, and organizational safeguards designed to protect information against unauthorized access, loss, misuse, or alteration. Security measures may include:</p>
          <ul>
            <li>Access controls</li>
            <li>Encrypted communications</li>
            <li>Secure infrastructure environments</li>
            <li>Monitoring systems</li>
            <li>Internal data protection procedures</li>
          </ul>
          <p className="pp-muted">However, no method of internet transmission or electronic storage is completely secure.</p>
        </div>

        <div className="pp-card" id="retention">
          <h2>8. Data Retention</h2>
          <p>KoshaX retains personal data only for as long as necessary to provide the Platform, comply with legal obligations, resolve disputes, and enforce agreements. Retention periods may vary depending on the type of information and applicable legal requirements.</p>
          <p className="pp-muted">When information is no longer required, it may be deleted or anonymized.</p>
        </div>

        <div className="pp-card" id="rights">
          <h2>9. User Rights</h2>
          <p>Subject to applicable law, users may have the right to:</p>
          <ul>
            <li>Request access to their personal information</li>
            <li>Request correction of inaccurate data</li>
            <li>Request deletion of personal data</li>
            <li>Withdraw consent for certain processing activities</li>
            <li>Request restriction of processing</li>
          </ul>
          <p>Users may exercise these rights by contacting KoshaX using the contact details provided below. Requests will be handled in accordance with applicable laws.</p>
        </div>

        <div className="pp-card" id="kids">
          <h2>10. Children's Privacy</h2>
          <p>The Platform is not intended for individuals under the age of 18 years. KoshaX does not knowingly collect personal information from minors. If we become aware that personal information from a minor has been collected without authorization, we will take steps to delete such information.</p>
        </div>

        <div className="pp-card" id="thirdparty">
          <h2>11. Third-Party Links and Services</h2>
          <p>The Platform may contain links to third-party websites or services. KoshaX is not responsible for the privacy practices or content of such third-party services. Users are encouraged to review the privacy policies of any external services they access.</p>
        </div>

        <div className="pp-card" id="changes">
          <h2>12. Changes to This Privacy Policy</h2>
          <p>KoshaX may update this Privacy Policy from time to time to reflect changes in technology, legal developments, or improvements to our services. Updated versions will be published on the Platform with a revised "Last Updated" date.</p>
          <p className="pp-muted">Continued use of the Platform after such changes constitutes acceptance of the updated policy.</p>
        </div>

        <div className="pp-card" id="governing">
          <h2>13. Governing Law</h2>
          <p>This Privacy Policy shall be governed by and interpreted in accordance with the laws of India.</p>
        </div>

        <div className="pp-card" id="contact">
          <h2>14. Contact Information</h2>
          <p>
            <strong>KoshaX Technologies Private Limited</strong><br />
            <span className="pp-muted">WeWork Eldeco Centre, Block A, Shivalik Colony, Malviya Nagar (South Delhi), New Delhi, South Delhi- 110017, Delhi</span><br />
            Email: <a href="mailto:compliance@koshax.com">compliance@koshax.com</a><br />
            Website: <a href="https://www.koshax.com" rel="noopener noreferrer">https://www.koshax.com</a>
          </p>
        </div>

      </div>

      <div className="pp-footer">
        <div className="pp-wrap pp-muted">
          &copy; {new Date().getFullYear()} KoshaX. All rights reserved.
        </div>
      </div>
    </div>
  );
};

export default PrivacyPolicyPage;
